version: 2.1

orbs:

jobs:  
  configure_infrastructure: 
    docker:
      - image: python:3.10.5-alpine3.16
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["74:7a:ac:99:82:f6:ee:96:e3:0c:00:f0:b9:6e:fe:e6"] # You can get this ID in the section where you registered the SSH Key
      - run:
          name: Install ansible
          command: |
            # install the dependencies needed for your playbook
            apk add --update ansible 
      - run:
          name: Run playbook and Configure server
          command: |
            ansible-playbook -i inventory.txt main.yml
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      - configure_infrastructure