version: 2.1

orbs:

jobs:  
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["a6:5e:08:02:40:3b:2b:18:92:d9:f9:7b:33:94:18:81"] # You can get this ID in the section where you registered the SSH Key
      - run:
          name: Install ansible
          command: |
            # install the dependencies needed for your playbook
            apk add --update ansible 
      - run:
          name: Run playbook and Configure server
          command: |
            ansible-playbook -i inventory.txt main.yml
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      - configure_infrastructure